      - name: 打包为 MintNTE.exe（带图标）
        shell: powershell
        run: |
          # 确认图标文件存在（日志中会打印出来）
          if (Test-Path "Image/logo/titlelogo.ico") {
            Write-Host "图标文件存在"
          } else {
            Write-Host "图标文件不存在！"
            exit 1
          }
          pyinstaller --noconfirm --onefile `
            --name MintNTE `
            --icon "Image/logo/titlelogo.ico" `
            --add-data "Image;Image" `
            --add-data "core;core" `
            --add-data "Module;Module" `
            --add-data "UI;UI" `
            --add-data "updater;updater" `
            --add-data "tools;tools" `
            --add-data "version.txt;." `
            --hidden-import=pygame `
            --hidden-import=pydirectinput `
            --hidden-import=keyboard `
            --hidden-import=mouse `
            --hidden-import=cv2 `
            --hidden-import=numpy `
            --hidden-import=PIL `
            --hidden-import=win32gui `
            --hidden-import=dxcam `
            --collect-all dxcam `
            --collect-all pydirectinput `
            main.py